spring:
  datasource:
#    h2 setting
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false